### ISSUE TITLE
Implment addresschooser with autocomplete from maptimize

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#57] opened 2011-08-18 08:22 UTC
--orig 157 by espaan

phenomenon¶
A nice addresschooser can be found here (MIT licensed)  http://addresschooser.maptimize.com/example/with_prototype.html

reason¶
Easier choice of the location you want to show. For hte Geocoding part as an extra option besides clicking on the map

recommendation¶
Check this feature out and see if it is easy to implement.

Attachments

Change History
comment:1 Changed 8 months ago by espaan 
    ■Milestone changed from 4.0.0 to 4.1.0

**Comment by Guite** [comment] 2018-08-21 15:50
Closing as duplicate of #53

**Closed by Guite** 2018-08-21 15:50 UTC
Labels: Feature
