### ISSUE TITLE
"Manage Content" pages fail

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#306] opened 2018-10-03 03:31 UTC
I've installed the new Content release on the latest Zikula release.
Content 5.0.1 / Zikula 2.0.11 / Symfony 3.4.14 / PHP 5.6.38-1+ubuntu16.04.1+deb.sury.org+2

I can create a page but no links or ajax on the Manage Content pages are functional.  Even on the sample page no content items are loaded.

Seems to me some javascript is missing.  I tried running composer but it says Nothing to install.

Does the new release require Zikula from master?

**Comment by robbrandt** [comment] 2018-10-03 03:41
Console output

351eff865f84aa4cffaaa2356365da891186400.js:2016 Uncaught SyntaxError: Unexpected token ;
routing?callback=fos.Router.setData:1 Uncaught ReferenceError: fos is not defined
    at routing?callback=fos.Router.setData:1
(anonymous) @ routing?callback=fos.Router.setData:1
zikula_javascript:5 Uncaught ReferenceError: Translator is not defined
    at zikula_javascript:5
(anonymous) @ zikula_javascript:5

**Comment by robbrandt** [comment] 2018-10-03 04:13
When I installed this "release" version, I deleted what I previously had in app/Resources/ZikulaContentModule, presuming that these would be rolled into the release.  And indeed, there isn't an app/Resources/ZikulaContentModule dir in the release.  But maybe something didn't get included?

**Comment by Guite** [comment] 2018-10-03 06:00
Try deleting `/web/js/`, refs https://github.com/zikula/core/issues/3804

**Comment by Guite** [comment] 2018-10-03 06:01
Also try setting `zikula_asset_manager.combine: false` in your `/app/config/custom_parameters.yml`.

**Comment by Portugao** [comment] 2018-10-03 09:01
Are you able to change php version to 7.0 or higher?

**Comment by robbrandt** [comment] 2018-10-03 16:47
Neither deleting /web/js/ nor setting zikula_asset_manager.combine: false worked.

I don't have a multi-php configuration on my server (yet) and this one is still running 5.6.  I know I have to deal with this soon, but it can't be until early 2019.

**Comment by Guite** [comment] 2018-10-03 18:38
If possible send me a mail providing some login credentials. I would like to take a look at the problem, maybe I see something...

**Comment by robbrandt** [comment] 2018-10-03 19:09
Sent via Slack

**Comment by Guite** [comment] 2018-10-03 19:19
The problem is indeed related to the asset combination functionality.

Because for example this code https://github.com/zikula-modules/Content/blob/master/src/app/Resources/ZikulaContentModule/public/js/ZikulaContentModule.PageEditing.js#L198-L203 becomes:

```
    var actions =;;; `
        <div;;; class="btn-group btn-group-sm pull-right";;; role="group">
            <button;;; type="button";;; class="btn btn-default change-styles";;; title="${Translator.__('Styling classes')}"><i;;; class="fa fa-paint-brush"></i> ${Translator.__('Styling classes')}</button>
            <button;;;;;; type="button";;; class="btn btn-default delete-section";;; title="${Translator.__('Delete section')}"${deleteState}><i;;; class="fa fa-trash-o"></i> ${Translator.__('Delete section')}</button>
        </div>;;;;;;
    `
```

**Comment by Guite** [comment] 2018-10-03 19:28
Problem solved by reuploading the corrupt file. Closing.

**Closed by Guite** 2018-10-03 19:28 UTC
