### ISSUE TITLE
Edit fail: failed to decode form includes

### ISSUE THREAD

**Issue by pheski** [zikula-modules/Content#166] opened 2015-12-22 19:27 UTC
I have been having issues with editing Content.

If I Start with my list of Content pages and try to edit one by clicking on the page and then on the arrow to the right of 'HTML markup text [ID 4], I get : "Error! Unknown content-ID"

If I start with the displayed document on the site and try to edit it there, I get a server 500 error:
Failed to decode form includes - this should not have happened
500 Internal Server Error - Exception
The first item in stack trace (of 22) is:
in lib/legacy/Zikula/Form/View.php at line 958

    public function decodeIncludes()
    {
        if (!isset($_SESSION['__forms'][$this->formId]['includes'])) {
            throw new Exception('Failed to decode form includes - this should not have happened');
        }
        $this->includes = $_SESSION['__forms'][$this->formId]['includes'];

The only way I seem to be able to edit is to clone the content, edit the cloned content, save it, then inactivate the old version leaving the new version in place.

**Comment by Guite** [comment] 2016-08-20 11:55
Which core version? Which Content version?

**Comment by pheski** [comment] 2016-08-20 12:14
That was 9 months ago. I was trying to recreate some 1.3.x sites in 1.4.x core. It was probably 1.4.0 or 1.4.1 and whichever Content was alleged to be current here on GIT. I have largely abandoned my Zikula sites, either letting them sit or moving to other tools, though I still have hope that Zikula will rise from the ashes and am working on gaining some coding competence so I can help... I will have to go back and see if I still have a site where this is happening.

**Comment by pheski** [comment] 2016-08-20 12:16
Zikula 1.4.0 and Content 4.2.1. It was a clean install of 1.4.0, not an upgrade from a 1.3.x core.

**Comment by Guite** [comment] 2016-08-20 12:16
I think this is a duplicate of #170 which I fixed this morning. Closing.

**Closed by Guite** 2016-08-20 12:16 UTC
